version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]
      - name: record_updated_at
        tests: [not_null]
      - name: cdc_operation
        tests:
          - accepted_values:
              arguments:
                values: ["r", "c", "u", "d"]

  - name: stg_accounts
    columns:
      - name: account_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id
      - name: account_type
        tests:
          - accepted_values:
              arguments:
                values: ["SAVINGS", "CHECKING"]
      - name: balance
        tests: [not_null]
      - name: record_updated_at
        tests: [not_null]

  - name: stg_transactions
    columns:
      - name: transaction_id
        tests: [not_null, unique]
      - name: account_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_accounts')
                field: account_id
      - name: transaction_type
        tests:
          - accepted_values:
              arguments:
                values: ["DEPOSIT", "WITHDRAWAL", "TRANSFER"]
      - name: amount
        tests: [not_null]
      - name: status
        tests:
          - accepted_values:
              arguments:
                values: ["COMPLETED", "PENDING", "FAILED"]
