version: 2

sources:
  - name: raw
    description: Bronze layer loaded from MinIO parquet files
    database: BANKING
    schema: RAW
    tables:
      - name: customers
        columns:
          - name: id
            tests: [not_null]
          - name: _cdc_op
            tests:
              - accepted_values:
                  arguments:
                    values: ["r", "c", "u", "d"]

      - name: accounts
        columns:
          - name: id
            tests: [not_null]
          - name: customer_id
            tests: [not_null]
          - name: _cdc_op
            tests:
              - accepted_values:
                  arguments:
                    values: ["r", "c", "u", "d"]

      - name: transactions
        columns:
          - name: id
            tests: [not_null]
          - name: account_id
            tests: [not_null]
          - name: txn_type
            tests:
              - not_null
              - accepted_values:
                  arguments:
                    values: ["DEPOSIT", "WITHDRAWAL", "TRANSFER"]
